### ISSUE TITLE
I read the source and find a Bug

### ISSUE THREAD

**Issue by kira8565** [sindresorhus/onetime#1]
```js
var onetime = require('onetime');

var i = 0;

var foo = onetime(function (a) {
    i++;
    a = a + i;
    return a;
});

console.log(foo(1));
console.log(foo(2));
console.log(foo(3));
```
Hello,When I use this moudles，I Think I can get the value as 0 every time,But I get the result like this :2,2,2

**Comment by SamVerschueren** [comment]
`2` is the correct result.

1. `i` is `0` at the start
2. You call the function with value `1` the first time, so `a=1`
3. `i` is incremented to 1
4. `a+i = 1+1 = 2`

**Comment by kira8565** [comment]
console.log(foo(1));  ==>2  is correct
but console.log(foo(2));==>2 ?? does't it equal 3 ?because the i is 0 at start and become 1 after,and a is equal 2 ,so 1+2=3

**Comment by SamVerschueren** [comment]
This is the description of the module:

> When called multiple times it will return the return value from the first call.
